title: Jaydee's Blog
author: jaydee323
email: tbc
description: > # this means to ignore newlines until "baseurl:"
  Fiddle playing beginning programmer
# social links
twitter_username: dna
github_username:  jaydee323

show_excerpts: false # set to false to remove excerpts on the homepage
